import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { Appbar } from "@/components/Appbar";
import { Providers } from "./provider";
import { Toaster } from "@/components/ui/toaster"
import { Footer } from "@/components/Footer";
import { BackgroundProvider } from "@/providers/backgroundProvider";
import { NavbarStateControlProvider } from "@/providers/navbarStateControlProvider";

const appFont = Ubuntu({subsets: ["latin"], weight:["400", "500", "700"]});
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${appFont.className} min-h-screen `}>
        <Providers>
          <Appbar/>
              <NavbarStateControlProvider />
                {children}
              <Footer />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
};