# .github/workflows/deploy-supabase-function.yml
name: Deploy Function

on:
  push:
    branches:
      - dev
    paths:
      - "supabase/functions/**"


jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy to supabase
        run: supabase functions deploy --project-ref $PROJECT_ID

      - name: Update Function URL in Database
        run: |
          FUNCTION_URL=https://$PROJECT_ID.supabase.co/functions/v1/your-function-name
          
          curl -X POST "https://${{ secrets.SUPABASE_PROJECT_ID }}.supabase.co/rest/v1/dynamicCnfig" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_KEY }}" \
            -H "Content-Type: application/json" \
            -H "Prefer: resolution=merge-duplicates" \
            -d "{\"key\": \"prod_edge_function_url\", \"value\": \"$FUNCTION_URL\"}"